version: '3.8'

services:
  cdc-lakehouse-app:
    build: .
    container_name: cdc-lakehouse-core
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - KAFKA_BOOTSTRAP_SERVERS=redpanda:9092
    depends_on:
      - redpanda
    restart: always

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.10
    container_name: redpanda-cdc-broker
    ports:
      - "9092:9092"
      - "9644:9644"
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://localhost:9092
